### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by efeichen**
This is basically a clone and there's still a lot to be done in regards to styles and functionalities but I want this to be the MVP and we can improve from here.

### CODE REVIEW

**Comment by lisalluo** [comment]
this looks great so far! can you make sure it looks good for smaller screen sizes?

**Comment by efeichen** [comment]
What do you think the behavior for the table should be on mobile? Because there are more fields for this table than the HackXX table just have it shrink prob won't work so I'm thinking have it overflow and allow user to scroll horizontally to see the rest of the table.

You can check out what that looks like on your phone here: http://needy-gun.surge.sh/

Let me know what you think! :)

**Comment by lisalluo** [comment]
maybe something we can consider is not including the desired prizes? since this website is mainly for hackers to use to find their demoing table, it's not necessary to have this info.

**Comment by subhankar-panda** [comment]
search! search is very helpful. maybe showing the devpost link would also be nice?

**Comment by RedbackThomson** [comment]
> search! search is very helpful. maybe showing the devpost link would also be nice?

Hyperlinks on the project name would suffice.

**Comment by efeichen** [comment]
> search! search is very helpful.

I'll implement that in another PR. I want this one to be just styling related only

> maybe something we can consider is not including the desired prizes?

But do we still wanna give users the freedom to have whatever field they want in their data? I'm fine with people just following our schema but I wanna hear you guys' opinion as well.

**Comment by lisalluo** [comment]
> But do we still wanna give users the freedom to have whatever field they want in their data? I'm fine with people just following our schema but I wanna hear you guys' opinion as well.

That's a good point. I think it's a good idea to let users pick what columns of their data to display, since other people might use this website a little differently than us. In that case, I like what we have now with the horizontal scrolling.

**Comment by efeichen** [comment]
Ok then I shall leave the page as it is right now. I do like the idea of having the DevPost URL to just be linked to the project name instead of having a separate column for it though. Maybe in the future that'll be the default behavior and organizers can toggle it on or off.

I'll make a separate issue to list out the TODOs and ideas, but if there's no more feedback regarding styling then I'll merge?

**Review by lisalluo — APPROVED** [review]
looks good!

**Pull request merged**
